# Generated by Django 3.2.3 on 2021-06-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
