# Generated by Django 3.2.3 on 2021-06-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210607_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='chapter',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
