# Generated by Django 3.2.3 on 2021-06-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210612_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unlocked_chapters',
            field=models.ManyToManyField(to='core.Chapter'),
        ),
    ]
