# Generated by Django 3.2.3 on 2021-06-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_unlocked_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
