# Generated by Django 3.2.3 on 2021-06-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_chapter_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_books',
            field=models.ManyToManyField(blank=True, to='core.Book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unlocked_chapters',
            field=models.ManyToManyField(blank=True, to='core.Chapter'),
        ),
    ]
