# Generated by Django 3.2.3 on 2021-06-13 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bookstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstatus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='background_color',
            field=models.CharField(blank=True, choices=[('White', 'Белый'), ('Black', 'Черный'), ('Red', 'Красный'), ('Blue', 'Синий'), ('Green', 'Зеленый'), ('Brown', 'Коричневый')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='brightness',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='distance_between_lines',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='font_size',
            field=models.CharField(blank=True, choices=[('Standart', 'Стандартный'), ('Big', 'Большой'), ('Very big', 'Очень большой')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='side_padding',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='text_color',
            field=models.CharField(blank=True, choices=[('White', 'Белый'), ('Black', 'Черный'), ('Red', 'Красный'), ('Blue', 'Синий'), ('Green', 'Зеленый'), ('Brown', 'Коричневый')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, choices=[('White', 'Белая'), ('Sepia', 'Сепия'), ('Night', 'Ночная'), ('Custom', 'Пользовательская')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Мужской'), ('Female', 'Женский')], max_length=30, null=True),
        ),
    ]
